### ISSUE TITLE
Is running as root really required?

### ISSUE THREAD

**Issue by igo95862** [Emanem/linux-hunter#12]
For me it runs fine without root. (on Arch Linux)

> Unforutnately looks like CAPCOM and/or wine/Proton are protecting memory, hence this requires sudo access when running.

Highly doubtful.

The most likely reason it does not want to run for you as root are AppArmor or SELinux. (depending if you are on Ubuntu or Fedora)

Try setting the CAP_SYS_PTRACE capability on the linux-hunter executable:  `sudo setcap cap_sys_ptrace=ep ./linux-hunter`

**Comment by Emanem** [comment]
Try this - and if this works, then please add to the README.md.

**Comment by igo95862** [comment]
> Try this - and if this works, then please add to the README.md.

I can't test because it works without root straight away for me.

I would modify README to tell people use root or capability only if it does not work out of box.

**Comment by Emanem** [comment]
Ok then, please go ahead and submit a pull request.
