### ISSUE TITLE
Can't make a package in Arch anymore

### ISSUE THREAD

**Issue by main-rouge** [Emanem/linux-hunter#18]
This used to work fine a few months ago but now trying to make a package gives me this:
https://gist.github.com/main-rouge/0d2d1a8172304335006918b7bf9fd66a

**Comment by Emanem** [comment]
Hi, give it a shot from latest master head - I should have patched it.

**Comment by Snogard** [comment]
i just tested and building works for me

**Comment by main-rouge** [comment]
Thx it now builds and works perfectly
btw I can also confirm sudo isn't necessary on Arch (wasn't necessary on fedora either from what I remember)

**Comment by Emanem** [comment]
Excellent!

Submit a PR with changes in README.md in terms of instructions and will be happy to merge!
